version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8
    steps:
      - checkout
      # install theme
      - run: git submodule update --init --recursive
      # install hugo
      - run: go get github.com/kardianos/govendor
      - run: govendor get github.com/gohugoio/hugo
      - run: go install github.com/gohugoio/hugo
      # install publish
      - run: mkdir -p content
      - run: hugo
      - run: cd DeNATECHSTUDIO.github.io && git add -A
      - run: cd DeNATECHSTUDIO.github.io && git commit -m 'Publish by CircleCI'
      - run: cd DeNATECHSTUDIO.github.io && git push origin master
